### ISSUE TITLE
problem to compile binutils as static library

### ISSUE THREAD

**Issue by nanzano** [Groundworkstech/pybfd#10]
Hi, I am new with library linking, so I didn't understand what you meant by ""The only rules to follow are that it must be compiled as a static library with PIC (Position-Independent Code) enabled"", tried to google how to do it and didn't get an appropriate method.
Thanks

**Comment by fruss** [comment]
Hi, that paragraph refers to the requirement on how [binutils](http://ftp.gnu.org/gnu/binutils/) has to be compiled to be able to correctly works with pybfd.

Specifically, _static library_ means that the resulting binary library will have no external dependencies (in some cases, that statement is not totally true... but believe me that an static compilation will "minimize" the dependencies), all the needed code will be resolved at compile-time and embedded in the resulting binary object itself. (more info at [here](https://en.wikipedia.org/wiki/Static_library))

Moreover, *PIC (Position-Independent Code)" refers to specific compilation/code-generation technique which let you to generate machine code that will be properly executed regardless of it absolute position in the address space. In other words, there is no usage of absolute addressing in any machine instruction, and all the references will be expressed relative to a specific anchors like the current instruction pointer. (more info at [here](https://en.wikipedia.org/wiki/Position-independent_code)]

You can configure _binutils_ to be compiled static and with pic support and supporting all the architectures using these options for the _configure_ script,
--enable-targets=all --disable-nls --disable-shared --enable-static
- **--enable-targets=all** : will compile all targets/architectures
- **--disable-nls** : turn-off internationalization
- **--disable-shared** : disable support of shared libraries
- **--enable-static** : add support of static build.

**Comment by nanzano** [comment]
Thanks you very much I will try it
